[package]
name = "vfio-run"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0"

[dependencies]
anyhow = "1.0.86"
clap = { version = "4.5.9", features = ["derive"] }
ctrlc = "3.4.4"
log = "0.4.22"
nix = {version = "0.29.0", features = ["user", "fs"] }
smbios-lib = "0.9.1"
stderrlog = "0.6.0"
