[package]
name = "vfio-run"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0"

[dependencies]
anyhow = "1.0.72"
clap = { version = "4.3.19", features = ["derive"] }
ctrlc = "3.4.1"
log = "0.4.19"
nix = {version = "0.27.1", features = ["user"] }
stderrlog = "0.5.4"
